server:
  port: 8081

spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
          driver-class-name: com.mysql.jdbc.Driver


  application:
    name: yml
  #profiles:
   # include:
    #  - eureka
    #  -
  mvc:
    throw-exception-if-no-handler-found: true     #出现错误时，直接抛出异常（全局异常处理）
  resources:
    add-mappings: false    #不要为工程中的资源文件建立映射（全局异常处理）



eureka:
  client:   #客户端配置
    service-url:
      default-zone: http://zhouqi:123456@localhost:8080/eureka  #Eureka地址
    register-with-eureka: true            #客户端注册到Eureka
    fetch-registry: true                  #客户端从Eureka拿到注册的列表信息
    registry-fetch-interval-seconds: 1    #Eureka客户端刷新本地缓存时间
  instance:   #实例配置
    prefer-ip-address: true   #以IP地址方式注册
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}  #实例ID


feign:
  hystrix:
    enabled: true       #Feign开启熔断器



#暴露端点，Hystrix-Dashboard监听需要
management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: ALWAYS


mybatis-plus:
  type-enums-package: com.galaxyt   #枚举包扫描


